### ISSUE TITLE
.pdf File not opening

### ISSUE THREAD

**Issue by bitsavvy** [owncloud/files_pdfviewer#102]
Hi there,

We get the following error when trying to open a .pdf file:
PDF.js v1.0.712 (build: 6969ed4)
Message: InvalidPDFException

We are on the latest version of Owncloud 8.2.2 -- tested in Firefox & Safari and getting the same erro in both.

Could you possibly assist?

Kind regards
Francois Wessels

**Comment by LukasReschke** [comment]
Please provide the PDF file.

**Comment by bitsavvy** [comment]
Hi there,

Thanks for the reply -- even the standard OwnCloud User Manual does not open. Other documents are client sensitive so cannot really provide you with examples but here is the manual. Don't know if that will help?

What is further worrying that immediately after the error occurs I am logged out of owncloud and must login again if I want to continue.

Any help will be greatly appreciated.

Kind regards
Francois Wessels

[ownCloud_User_Manual.pdf](https://github.com/owncloud/files_pdfviewer/files/160354/ownCloud_User_Manual.pdf)

**Comment by LukasReschke** [comment]
That is strange and seems more like an environment specific issue. Any chance you can provide me with an user account on that instance? You can find my mail address in my profile.

**Comment by Peac** [comment]
I have the same problem on ownCloud version 8.2.3.

**Comment by don-philipe** [comment]
Had the same problem recently with ownCloud 8.2.2. It occured in a shared folder for the account with whom the folder was shared. After recreating that account and sharing again with the account the error was gone an everything was alright then.
Maybe this is a problem with server-side encryption after changing the shared-with-accounts password? The following error showed up in my log:

` Error 	no app in context 	Exception: {"Exception":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException","Message":"multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02","Code":0,"Trace":"#0 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/apps\/encryption\/lib\/keymanager.php(406): OCA\\Encryption\\Crypto\\Crypt->multiKeyDecrypt('N?????w???????...', '?\\;Q?D{\"?D???J?...', '-----BEGIN RSA ...')\n#1 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/apps\/encryption\/lib\/crypto\/encryption.php(419): OCA\\Encryption\\KeyManager->getFileKey('\/sharingaccount\/files...', 'sharedwithaccount')\n#2 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/storage\/wrapper\/encryption.php(289): OCA\\Encryption\\Crypto\\Encryption->isReadable('\/sharingaccount\/files...', 'sharedwithaccount')\n#3 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/storage\/wrapper\/wrapper.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->isReadable('files\/folderwithpdfs...')\n#4 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/apps\/files_sharing\/lib\/sharedstorage.php(256): OC\\Files\\Storage\\Wrapper\\Wrapper->isReadable('files\/folderwithpdfs...')\n#5 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/storage\/wrapper\/wrapper.php(161): OC\\Files\\Storage\\Shared->isReadable('folderwithpdfs...')\n#6 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/storage\/wrapper\/availability.php(170): OC\\Files\\Storage\\Wrapper\\Wrapper->isReadable('folderwithpdfs...')\n#7 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/storage\/wrapper\/wrapper.php(161): OC\\Files\\Storage\\Wrapper\\Availability->isReadable('folderwithpdfs...')\n#8 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/view.php(1023): OC\\Files\\Storage\\Wrapper\\Wrapper->isReadable('folderwithpdfs...')\n#9 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/view.php(399): OC\\Files\\View->basicOperation('isReadable', '\/folderwithpdfs...')\n#10 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files\/filesystem.php(672): OC\\Files\\View->isReadable('\/folderwithpdfs...')\n#11 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files.php(164): OC\\Files\\Filesystem::isReadable('\/folderwithpdfs...')\n#12 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/files.php(90): OC_Files::getSingleFile(Object(OC\\Files\\View), '\/folderwithpdfs...', 'pdffile.pdf...', false)\n#13 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/apps\/files\/ajax\/download.php(53): OC_Files::get('\/folderwithpdfs...', Array, false)\n#14 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/vhosts...')\n#15 [internal function]: __lambda_func(Array)\n#16 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/private\/route\/router.php(291): call_user_func('?lambda_235', Array)\n#17 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#18 \/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/index.php(39): OC::handleRequest()\n#19 {main}","File":"\/var\/www\/vhosts\/mydomain.org\/owncloud\/www\/apps\/encryption\/lib\/crypto\/crypt.php","Line":564}`

**Comment by don-philipe** [comment]
Well, I have to correct my previous post. The problem has nothing to do with server-side-encryption.

I found out that the problem is more browser related as shown in [this](https://github.com/mozilla/pdf.js/issues/6790) issue. Setting `network.cookie.cookieBehavior` in Firefox config to `0` solves the problem. Alternatively one can set an Exception for the website.

**Comment by PVince81** [comment]
please try again with 0.9.0 as we've updated the [pdf.js](https://github.com/mozilla/pdf.js) library
