### ISSUE TITLE
How about supporting all Office document preview via on-the-fly converting pdf?

### ISSUE THREAD

**Issue by xinqianli** [owncloud/files_pdfviewer#105]
How about supporting all Office document preview via on-the-fly converting pdf, just as OpenKM? We often need to preview instead of download.

**Comment by PVince81** [comment]
Office documents can already be previewed using Collabora or OnlyOffice.

There is no clear benefit to converting to PDF.

Also, this app is just a wrapper around [pdf.js](https://github.com/mozilla/pdf.js).
Anything that would require conversions is more involved and outside the scope of this app. (could be a different app)
