### ISSUE TITLE
Update PDF.js to version 1.3.91 or above.

### ISSUE THREAD

**Issue by yurydelendik** [owncloud/files_pdfviewer#107]
See available releases at https://github.com/mozilla/pdf.js/releases

**Comment by LukasReschke** [comment]
Will do. Thanks for the hint :)

**Comment by michaelstingl** [comment]
I've seen the latest release is: [v1.4.20](https://github.com/mozilla/pdf.js/releases)

@PVince81

00006176

**Comment by PVince81** [comment]
Tried to update to 1.4.20 and then 1.5.188 (prerelease).

But this breaks. The PDF viewer refuses to use our own provided PDFJS.workerSrc.

Well, pdf.js does read the value, but later on when the viewer.js initializes, it completely overrides the value of PDFJS.workerSrc with a relative path that cannot work.

Not sure yet if it's an upstream bug or whether we need to do this differently.
I'll submit a PR with the current state.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/files_pdfviewer/pull/126
