### ISSUE TITLE
Update pdfjs to current stable due to umlaut Bug

### ISSUE THREAD

**Issue by dirkpape** [owncloud/files_pdfviewer#115]
With the currently included version of pdf.js (1.1.469)in ) oc 9.0.1 some Umlauts in German documents are not printed correctly.
I tested the current stable version of pdf.js (1.4.20) and it does well.
Will it be possible to bump up the version already for the next minor release of owncloud or will we have to wait for 9.1 - which would be a pity.

![voila_capture 2016-04-29_02-25-17_pm](https://cloud.githubusercontent.com/assets/5426508/14916004/3ea92acc-0e17-11e6-9c19-7e89b28f1e0e.png)
![voila_capture 2016-04-29_02-25-45_pm](https://cloud.githubusercontent.com/assets/5426508/14916006/42c054dc-0e17-11e6-9a04-9be23ea60fc8.png)

**Comment by dirkpape** [comment]
still not fixed in 9.1 :-(

**Comment by dirkpape** [comment]
will this be fixed for oc 9.2 or nextcloud 10?

**Comment by DeepDiver1975** [comment]
@dirkpape you are welcome to contribute and submit a pull request - THX

**Comment by dirkpape** [comment]
@DeepDiver1975 Sorry, I would like to, but I am not able to do so (from time and from lack of experience in owncloud development). I also understood that @LukasReschke  self-assigned this already.

**Comment by LukasReschke** [comment]
I'm not anymore with ownCloud.

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/files_pdfviewer/pull/146
