### ISSUE TITLE
tools button missing in templates/viewer.php

### ISSUE THREAD

**Issue by groniu** [owncloud/files_pdfviewer#116]
Why did you remove tools button ? It can coexist well with close button.
Can we have it back ?

**Comment by qwazix** [comment]
You can go add 

        <button id="secondaryToolbarToggle" class="toolbarButton" title="Tools" tabindex="36" data-l10n-id="tools">

in `apps/files_pdfviewer/templates/viewer.php` line 190 to bring it back. No other change is required. 

Please bring it back officially however.

**Comment by groniu** [comment]
Yeah, I've added on our OC installations at the time I've posted above but it would be easier not to have to add it after each upgrade. Its "'crucial" feature for some our users.

**Comment by groniu** [comment]
Please consider to bring it back after each upgrade i need to add it. I dont think it can brake anything

For others who need it add following code in `apps/files_pdfviewer/templates/viewer.php` after line 189 to bring back tools button 

`<button id="secondaryToolbarToggle" class="toolbarButton" title="Tools" tabindex="36" data-l10n-id="tools">
                <span data-l10n-id="tools_label">Tools</span>
              </button>`

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/files_pdfviewer/pull/149
