### ISSUE TITLE
Incremental backup on ownCloud

### ISSUE THREAD

**Issue by wbonifacio** [owncloud/files_pdfviewer#118]
The most important file that I have on my ownCloud server is my operational system database and its size is increased every day. During the synchronization process this file size changes often and can not be synchronized . Once you stop working, full synchronization starts, would be excellent if only upload the file changes. This file is 572MB and takes a long time to load limiting my bandwidth.

**Comment by DeepDiver1975** [comment]
This definitely the wrong repo. Please reopen in core or at the Forums.
