### ISSUE TITLE
Viewer fails to download PDF with CSP error in Firefox

### ISSUE THREAD

**Issue by ansemjo** [owncloud/files_pdfviewer#119]
### Steps to reproduce
1. Open any PDF in the PDF Viewer app
2. Click the download button in the top right corner
### Expected behaviour

File saving dialog should appear, prompting for name/path to save to or otherwise define an action to take.
### Actual behaviour

Nothing happens. Console logs a CSP error:

```
Content Security Policy: The page's settings blocked the loading of a resource at blob:https://own.DOMAIN.de/b34...a3e3 ("frame-src https://own.DOMAIN.de").
```

Directly downloading from file list works fine.
### Server configuration

Tested on two different and unrelated systems .. referred to as **1.** and **2.**.

**Operating system**:
1. Arch Linux `Linux 4.6.4-1-ARCH x86_64 GNU/Linux`
2. Ubuntu 14.04.4 LTS `Linux 3.13.0-042stab113.11 x86_64 GNU/Linux` (Plesk-Managed)

**Web server:**
1. NGINX `nginx/1.11.1` using the config from the [manual](https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_owncloud_9x.html?highlight=nginx#owncloud-in-the-webroot-of-nginx)
2. NGINX `nginx/1.11.1` (reverse proxy) + Apache `Apache/2.4.10 (Ubuntu)`

**Database:**
1. MariaDB `mysqld  Ver 10.1.14-MariaDB for Linux on x86_64`
2. MySQL `mysqld  Ver 5.5.49-0ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))`

**PHP version:**
1. PHP 7.0.9 `.. (fpm-fcgi) (built: Jul 20 2016 17:12:29)`
2. PHP 7.0.8 managed by Plesk `plesk-php70`

**ownCloud version:** (see ownCloud admin page)
1. ownCloud 9.1.0 (stable)
2. ownCloud 9.0.2 (stable)

**Updated from an older ownCloud or fresh install:**
Both updated from 8.*

**Where did you install ownCloud from:**
1. [Arch package in 'community'](https://www.archlinux.org/packages/community/any/owncloud/)
2. Through apt-get from [download.owncloud.org](http://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/) (in `sources.list.d/owncloud.list`)

**Signing status (ownCloud 9.0 and above):** Both report `No errors have been found.`
**List of activated apps:** Both use `files_pdfviewer: 0.8.1`
**The content of config/config.php:** _Will add this if really relevant .._
**Are you using external storage, if yes which one:** Both use additional local storage.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** The Ubuntu Box uses LDAP.
### Client configuration

**Browser:** Firefox 47.0.1
**Operating system:** Linux
#### Web server error log

No relevant log entries ...
#### ownCloud log (data/owncloud.log)

No relevant log entries ...
#### Browser log

```
Content Security Policy: The page's settings blocked the loading of a resource at blob:https://own.DOMAIN.de/a3b...ebc ("frame-src https://own.DOMAIN.de").
```

---
## Similar issue

I found this other, very similar issue #76. But it has very little information and is closed already, so I cannot say if it is related.
## Fix with nginx config

I could remedy the error on the Ubuntu Server with two lines in my nginx config, changing the `Content-Security-Policy` header:

```
proxy_hide_header Content-Security-Policy;
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src * blob:; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *";
```

.. i.e. hide Owncloud's header and use `frame-src * blob:;` instead of `frame-src *;`.

Haven't tried on the Arch Linux box yet but I assume it works similarly.
## Chromium works right away

Installed Chromium (`52.0.2743.82-1`) to test a different browser (also on Linux obviously) and it works right away, also **without** the above 'fix'. Meaning, there is no error in the developer console and the file is downloaded properly.

**Comment by felixboehm** [comment]
quick guesses:
1. https://github.com/owncloud/files_pdfviewer/blob/master/js/previewplugin.js#L150
2. https://github.com/owncloud/files_pdfviewer/blob/master/vendor/pdfjs/web/compatibility.js#L440

Can you set a js breakpoint and check these code pathes?

**Comment by dercorn** [comment]
Replacing https://github.com/owncloud/core/blob/master/lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php#L375 with
$policy .= ' blob:;';
fixed this issue for me.
Thanks to @felixboehm for pointing this out!

**Comment by PVince81** [comment]
Mind submitting this as PR ? Thanks

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27538
