### ISSUE TITLE
Special Characters in Filename cause 404 File Not Found Error

### ISSUE THREAD

**Issue by demaperera** [owncloud/files_pdfviewer#122]
**ownCloud v9** - Clicking the PDF file named _'ownCloud Manual'_ causes a 404 File Not Found error in pdf.js. Renaming the file to _'ownCloud'_ (without spaces) causes it to display correctly in the viewer. A weird layout issue also happens when this error is thrown, see the screenshot below.

![screen shot 2016-08-10 at 10 16 19 pm](https://cloud.githubusercontent.com/assets/11702548/17562353/2396bb64-5f48-11e6-8732-716982be6f35.png)

Error in Chrome Console:
`http://cloud.perera.io/index.php/core/preview.png?file=%2FownCloud+Manual.pdf&x=75&y=75&c=3cdd2e6fe60ed8561ba7b744b6c7cc1b&forceIcon=0 Failed to load resource: the server responded with a status of 404 (Not Found)
`

Since both _'+'_ and _'%20'_ are the URL equivalents of white spaces I cannot think of why a 404 error is being thrown. 

Please note that the PDF document correctly renders and displays when using a single word as the filename without special characters or white spaces.

This issue is present every time I do a clean installation of ownCloud, upload multiple PDF files and try to open them.

**Comment by DeepDiver1975** [comment]
Which version are you using?

I cannot reproduce this with master.

**Comment by felixboehm** [comment]
solved meanwhile
