### ISSUE TITLE
Enable "deep linking" to shared PDFs in OwnCloud

### ISSUE THREAD

**Issue by aeneby** [owncloud/files_pdfviewer#123]
PDF.js appears to support linking to specific destinations in a PDF using "#page=x" or "#nameddest=y" in the URLs, but I can't seem to achieve the same thing using OwnCloud's pdfviewer. Is it possible to pass these parameters on to PDF.js?

**Comment by aeneby** [comment]
Ping?

**Comment by PVince81** [comment]
From where would you get such link ? We can't expect users to manually craft such links.

If there is a way, please describe detailed steps.

**Comment by aeneby** [comment]
This was reported almost 2 years ago. Please just close the issue.
