### ISSUE TITLE
PDF Viewer in Web not displaying content

### ISSUE THREAD

**Issue by jclgs** [owncloud/files_pdfviewer#128]
Version: Owncloud 9.1

Here is the content of a PDF open from Adobe Reader.
![image](https://cloud.githubusercontent.com/assets/24614035/21279010/24347ade-c3ac-11e6-8c9c-fe32a628c9f9.png)

Here is the same content of a PDF open with the PDF viewer in OwnCloud.
![image](https://cloud.githubusercontent.com/assets/24614035/21279035/4d157980-c3ac-11e6-9ffb-c4ed6bd1f764.png)

You can see the color is not the same and missing info. 
Sorry, I cannot put more images because those contents are for internal business use.

What can cause that issue? Any idea?
Thanks

**Comment by jclgs** [comment]
Discover the issue is only in Chrome. Firefox works well. IE works well too.

**Comment by jclgs** [comment]
Also did a test with the Chrome Extension and the issue there too.

**Comment by jclgs** [comment]
We found the issue.

The issue is related with Chrome only and when the PDF is using Symbol Layer. As soon as we unlink Symbol Layer and generate a new PDF, the second picture with missing information is now printing the text?

Is it possible to get Symbol Layer working in  Chrome. It works in IE, Fifefox, Safari but not Chrome, one of the most use browser.

Waiting answer.
Thanks

**Comment by PVince81** [comment]
Please first try with the master version of the files_pdfviewer where the pdfjs library was updated. If that still doesn't work, might need to upgrade pdfjs again or submit a bug report directly to the pdfjs project.

**Comment by kdslkdsaldsal** [comment]
@jclgs @PVince81 Upstream report confirmed that those are bugs in Firefox and Chrome so this issue can be closed: https://github.com/mozilla/pdf.js/issues/8019

**Comment by PVince81** [comment]
Hmm, but once they fix it we need to update the bundled pdfjs lib so it work in ownCloud too.

**Comment by PVince81** [comment]
ok closing as dup of https://github.com/owncloud/files_pdfviewer/issues/130

**Comment by kdslkdsaldsal** [comment]
@PVince81 
> Hmm, but once they fix it we need to update the bundled pdfjs lib so it work in ownCloud too.

I might be wrong but if i'm reading https://github.com/mozilla/pdf.js/issues/8019 correctly both issues are browser bugs in Chrome and Firefox so it might be not needed to update the bundled pdfjs.
