### ISSUE TITLE
Bump pdfjs to v1.6.210 for oC 10

### ISSUE THREAD

**Issue by ghost** [owncloud/files_pdfviewer#130]
With https://github.com/owncloud/files_pdfviewer/issues/107 pdfjs was bumped to v1.4.20 IMHO this version is already outdated and at the time of the release of oC 10 nearly 15 months old.

Please consider bumping the pdfjs version to the latest stable release v1.6.210:

https://github.com/mozilla/pdf.js/releases/tag/v1.6.210

to avoid that such outdated components are shipped with oC 10

**Comment by kdslkdsaldsal** [comment]
@jclgs in https://github.com/owncloud/files_pdfviewer/issues/128 seems to have bumped the version of pdfjs to 1.6.210 within the app and it worked without the need to modify stuff like in #107

**Comment by PVince81** [comment]
Updated here https://github.com/owncloud/files_pdfviewer/pull/137 without further modifications.

A quick test with a simple PDF shows that it doesn't work.

Sadly, it seems it will still need to add back the previous hacks.

**Comment by PVince81** [comment]
Reopened here: https://github.com/owncloud/files_pdfviewer/issues/145
