### ISSUE TITLE
Add Rotate to PDF viewer

### ISSUE THREAD

**Issue by dpitulski** [owncloud/files_pdfviewer#138]
This is a slick interface and I am looking to use OC with the PDF viewer for a paperless project and would like to see a rotate PDF feature added.

Thank you.

**Comment by PVince81** [comment]
The interface is just a wrapper for the PDF.js library from Mozilla: https://mozilla.github.io/pdf.js/

I suggest you send your request there to add a button for rotation so ownCloud will get it once we update the library again.
