### ISSUE TITLE
Feature request: Disable pdf.js on iOS devices

### ISSUE THREAD

**Issue by voroyam** [owncloud/files_pdfviewer#141]
To avoid users trying to print their pdf documents when using the webUI on an iOS device, we should disable the pdf.js.

**Comment by michaelstingl** [comment]
I know no use case, where the JS-rendered PDF is better than the iOS system-default PDF viewer. Better show the PDF directly.

You only have limitations, like the problem @voroyam describes:
![img_0067](https://user-images.githubusercontent.com/214010/29456180-dde96b8c-8414-11e7-95f3-01b9493adc46.png)

**Workaround:**
Don't click the "Print" button, click the "Download" button instead. Then you can print using the default iOS printing feature.

**Comment by michaelstingl** [comment]
@LukasHirt @pmaier1 we discussed switching to browser-native PDF viewer. Only ownCloud-web or oC10 too?

**Comment by pmaier1** [comment]
Yeah, this decision was only for ownCloud Web. oC 10 will stay as it is.
