### ISSUE TITLE
Files_pdfviewer is not able to open a pdf file using branch release-0.9.0

### ISSUE THREAD

**Issue by davitol** [owncloud/files_pdfviewer#151]
Using files_pdf_viewer branch: https://github.com/owncloud/files_pdfviewer/tree/release-0.9.0 and ownCloud 10.0.9.RC3

Trying to open a pdf file, the browser do not show the file content

![screen shot 2018-07-12 at 10 01 20](https://user-images.githubusercontent.com/10596560/42622042-ac47907e-85bf-11e8-8132-2a924f7e02ef.png)
![screen shot 2018-07-12 at 10 00 35](https://user-images.githubusercontent.com/10596560/42622051-b20f88b8-85bf-11e8-8069-908ee9c94b1f.png)

**Comment by PVince81** [comment]
Fixed in https://github.com/owncloud/files_pdfviewer/pull/152
