### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_pdfviewer#153]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.click()`

- [ ] /js/previewplugin.js
- [ ] /js/vendor/pdfjs/web/viewer.js

`.focus()`

- [ ] /js/vendor/pdfjs/web/viewer.js

`.data()`

- [ ] /js/vendor/pdfjs/web/viewer.js

`.focus()`

- [ ] /js/vendor/pdfjs/web/viewer.js

`.attr()`

- [ ] /js/previewplugin.js

`.toggle()`

- [ ] /js/vendor/pdfjs/web/viewer.js

`.add()`

- [ ] /js/vendor/pdfjs/web/debugger.js
- [ ] /js/vendor/pdfjs/web/viewer.js

`.insertBefore()`

- [ ] /js/vendor/pdfjs/web/viewer.js

**Comment by PVince81** [comment]
pdfjs runs in an iframe AFAIK so we could ignore the ones in there

@VicDeo

**Comment by VicDeo** [comment]
@PVince81 not exactly. there is a JS that registers handlers by mime type

**Comment by PVince81** [comment]
@VicDeo yes, but the files listed in the original post are the ones that run inside the PDFJS iframe, so its jquery version is isolated so we shouldn't need to check that it's compatible with core's jquery ?

**Comment by PVince81** [comment]
all except `js/previewplugin.js` of course, this one we need to examine

**Comment by VicDeo** [comment]
No issues have been found
