### ISSUE TITLE
jQuery UI Upgrade

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_pdfviewer#158]
# jQuery UI Upgrade

See the full [upgrade 1.11. guide](https://jqueryui.com/upgrade-guide/1.11/)

See the full [upgrade 1.12. guide](https://jqueryui.com/upgrade-guide/1.12/)

## [1.11] (Core) Deprecated multiple

`.focus()`

- [x] js/vendor/pdfjs/web/viewer.js

## [1.12] (Core) Removed multiple

`.focus()`

- [x] js/vendor/pdfjs/web/viewer.js

**Comment by PVince81** [comment]
focus usages unrelated
