### ISSUE TITLE
Japanese is not displayed in PDF created with MAC OS X

### ISSUE THREAD

**Issue by devi69** [owncloud/files_pdfviewer#162]
### Steps to reproduce
1.Create PDF file with macOSX
2.Upload to ownCloud
3.Browse PDF with the files_pdfviewer application

Uploaded test file  
[mac_text_editor.pdf](https://github.com/owncloud/files_pdfviewer/files/2602686/mac_text_editor.pdf)

### Expected behaviour
PDF is displayed correctly including Japanese characters

### Actual behaviour
Japanese part is displayed as blank  

In ownCloud 9.1 (files_pdfviewer: 0.8.1), Japanese is also displayed correctly

### Server configuration

**Operating system**:  
CentOS Linux release 7.3.1611

**Web server:**  
nginx-1.12.1-1

**Database:**  
redis-3.2.10-2

**PHP version:**  
php-pdo-7.0.22-1  
php-fpm-7.0.22-1

**ownCloud version:** 
10.0.8

**Where did you install ownCloud from:**  
owncloud-10.0.8.tar.bz2 from owncloud.org

**List of activated apps:**

```
Enabled:
  - activity: 2.3.8
  - comments: 0.3.0
  - configreport: 0.1.1
  - customgroups: 0.3.6
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.4
  - notifications: 0.3.3
  - ocaudit: 0.1.0
  - provisioning_api: 0.5.0
  - security: 0.0.2
  - systemtags: 0.3.0
  - twofactor_totp: 0.4.4
  - updatenotification: 0.2.1
  - user_bulkregister: 0.1.0
  - user_ldap: 0.11.0
```

**ownCloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc_10.0.8",
        ],
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0
        },
        "datadirectory": "\/home\/data_10.0.8",
        "overwrite.cli.url": "https:\/\/oc_10.0.8",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "owncloud_10_0_8",
        "dbhost": "localhost:3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Tokyo",
        "installed": true,
        "theme": "",
        "ldapIgnoreNamingRules": false,
        "session_lifetime": 120,
        "session_keepalive": false
    }
}
```

### Client configuration

**Operating system:**  
macOS 10.13.1(create pdf file)

#### Nextcloud log (data/owncloud.log)
```
no logs
```

#### Browser log

I got the screen capture

· The state seen by Windows 10 viewer
![win_preview_image](https://user-images.githubusercontent.com/23556623/48820166-084e6480-ed97-11e8-8a2d-39f0d8d7987f.png)

· The state seen by files_pdfviwer
![oc_files_pdfviewer_image](https://user-images.githubusercontent.com/23556623/48820171-0e444580-ed97-11e8-8486-844ef0e65f75.png)

**Comment by devi69** [comment]
Hi.

A fix for files_pdfviewer has been made on Nextcloud.
With this fix, my sample file was displayed correctly.

Fix load of character maps # 140
https://github.com/nextcloud/files_pdfviewer/pull/140

ownCloud's files_pdfviewer is 0.9.0, The same fix does not seem to apply.

It would be nice if it could be displayed in the same way with ownCloud's files_pdfviewer.

**Comment by JanAckermann** [comment]
Confirm working with owncloud 10.7 and files_pdfviewer 1.2.0
