### ISSUE TITLE
PDF viewer 0.11.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_pdfviewer#178]
This is the server app release template, please copy the part below in a new ticket.
For instructions around app releases, see https://handbook.owncloud.com/releasing_apps.html

### Reason

- [x] PDF JS update: https://github.com/owncloud/files_pdfviewer/pull/177

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.11.0 Testplan" issue #179 

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC2' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch #179 

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by PVince81** [comment]
I'll branch this off the old tag to avoid the PHP limitation as we want this update to be compatible with OC < 10.2

**Comment by PVince81** [comment]
RC1 failed, was missing changelog

RC2 here: https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.0RC2

@phil-davis can you smoke test ?

**Comment by phil-davis** [comment]
@PVince81 0.1.0RC2 looks good. Test results in #179 
One minor issue that I noticed #180 - and that is not a regression, it happens in 0.9.0 and 0.10.0 also.

**Comment by PVince81** [comment]
cool, thanks.

**Comment by PVince81** [comment]
last PR for merge back https://github.com/owncloud/files_pdfviewer/pull/181
