### ISSUE TITLE
download of PDF file received as public link has name document.pdf

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_pdfviewer#180]
1) public link share a PDF file individually, e.g. `sample.php`
2) access the link
3) download the file using the ownCloud "Download" button
4) the file is downloaded with name `sample.php` - good
5) download with the download icon in the PDF viewer controls

### Actual behaviour
The downloaded file is called `document.pdf`

### Expected behaviour
The downloaded file is called `sample.pdf`

Tested on Chrome and Firefox browsers and `files_pdfviewer` 0.11.0RC2 0.10.0 0.9.0 - behaviour is the same on all versions and browsers.

If the public link share is a folder, and `sample.php` is in the folder, then it downloads with the correct file name.
If the individual file is shared internally with another user or group, then when a receiving user opens and downloads it, the file name is correct.

**Comment by davitol** [comment]
Works for me with oC 10.2.1. and files_pdfviewer: 0.11.1. Let's close the ticket and feel free to reopen if it is reproducible again
