### ISSUE TITLE
Upgrade the PDF JS

### ISSUE THREAD

**Issue by cdamken** [owncloud/files_pdfviewer#183]
Please upgrade the version 2.0.30 from 2019

**Comment by micbar** [comment]
@VicDeo The customer wants to open attachments inside pdf documents. He tested it with th version 2.3.0 of pdfjs.

Could we upgrade the library? This seems like a breaking change.

Please clarify.

**Comment by VicDeo** [comment]
@cdamken @micbar 2.3.0?
pdf.js project has Pre-release  v2.1.266 and Latest release v2.0.943 at the moment
https://mozilla.github.io/pdf.js/getting_started/#download
https://github.com/mozilla/pdf.js/releases

**Comment by cdamken** [comment]
Could you test it with the latest version?

**Comment by VicDeo** [comment]
@cdamken We use the latest v1 release. Blind switching to v2  breaks the viewer.

**Comment by VicDeo** [comment]
ok, 2.0 is not an option - it has unsafe evals inside that are blocked by our default CSP policy:
```
runtime-module.js:10 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```
We can't loose the default CSP policy, trying with 2.1 which has a Beta status currently

**Comment by micbar** [comment]
@VicDeo Ok, lets see what 2.1 is capable of.

**Comment by VicDeo** [comment]
@micbar trying 3 hours in a row so far... can't overload `workerSrc` like it was done here 
https://github.com/owncloud/files_pdfviewer/blob/master/js/workersrc.js#L20

All attempts  are ended like this:
![result](https://user-images.githubusercontent.com/991300/59537963-eec26500-8f00-11e9-84a3-a21d30f3e8e0.png)

**Comment by VicDeo** [comment]
@cdamken @micbar 
Good news: I managed to update the lib to v2.1 https://github.com/owncloud/files_pdfviewer/pull/184
Bad news: the oC part of the viewer is missing a part to work with attachments properly. 

Attachments are sent via data://protocol and do not belong to ownCloud filesystem directly so supporting them needs further research.

The easiest solution here is to download attachments instead of viewing them.

**Comment by micbar** [comment]
@VicDeo Is the 2.1 really a beta release?

**Comment by VicDeo** [comment]
https://mozilla.github.io/pdf.js/getting_started/#download
>Stable (v2.0.943)
Beta (v2.1.266)

**Comment by cdamken** [comment]
After clarifying: Its 2.0.30

**Comment by micbar** [comment]
@cdamken we need to wait until 2.1 is stable.
2.0.30 is not supported see https://github.com/owncloud/files_pdfviewer/issues/183#issuecomment-502165228

**Comment by pmaier1** [comment]
> @cdamken we need to wait until 2.1 is stable.

Looking at https://mozilla.github.io/pdf.js/getting_started/#download, 2.1 is now stable. Can we upgrade the lib now and will that fix the issue?

**Comment by micbar** [comment]
@VicDeo merged the PR.
Could we fix the original problem? Do you see it within a reasonable effort?

**Comment by VicDeo** [comment]
>Can we upgrade the lib now and will that fix the issue?

Status of 2.1.266 was changed from `Beta` into `Stable` https://github.com/mozilla/pdf.js/releases/tag/v2.1.266 but it has the same changeset inside.  So it won't.

**Comment by pmaier1** [comment]
> but it has the same changeset inside. So it won't.

Then seems we'll have to wait. Will 2.2 include the necessary changes?

**Comment by VicDeo** [comment]
@pmaier1 no, as it's a feature lack of the pdfviewer app. 
Embedded docs are provided using `data:` protocol and the app has never been able to display them.

**Comment by VicDeo** [comment]
I'm closing this issue as we merged the version bump
