### ISSUE TITLE
Allow full screen

### ISSUE THREAD

**Issue by fmkaiser** [owncloud/files_pdfviewer#188]
It would be very useful to be able to view PDFs in full screen / presentation mode.

This is actually supported in pdf.js, we would just need to add `allowfullscreen` to the iframe:

![allowfullscreen](https://user-images.githubusercontent.com/2922101/63493042-fed76180-c4ba-11e9-9b5f-b3509b7468a2.png)

(For a live demo see https://mozilla.github.io/pdf.js/web/viewer.html)

Is there a reason why that might be a bad idea?

Otherwise I would be happy to submit a pull request.

**Comment by JanAckermann** [comment]
Seems to be already implemented
