### ISSUE TITLE
PDF Viewer 0.11.1

### ISSUE THREAD

**Issue by micbar** [owncloud/files_pdfviewer#197]
### Reason

- Release needed for https://github.com/owncloud/enterprise/issues/3377

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.11.1Testplan" @davitol https://github.com/owncloud/files_pdfviewer/issues/204

### Documentation

- [x] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol https://github.com/owncloud/files_pdfviewer/

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Make sure, the current section has a date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close Milestone

**Comment by micbar** [comment]
@ChrisEdS FYI

**Comment by micbar** [comment]
RC1 in https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.1RC1

**Comment by davitol** [comment]
> RC1 in https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.1RC1

RC1 Tarball tested. See issues found while QA here: https://github.com/owncloud/files_pdfviewer/issues/204#issuecomment-564000397

@HanaGemela (cc @micbar )

**Comment by micbar** [comment]
@davitol RC2 in https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.1RC2

**Comment by davitol** [comment]
> @davitol RC2 in https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.1RC2

Tarball is QA-ready. Only issue spotted (not regression) https://github.com/owncloud/files_pdfviewer/issues/202 :shipit:

**Comment by micbar** [comment]
@settermjd We could display pdf attachments now.
Demo was already done.

**Comment by micbar** [comment]
@davitol Final is here https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.1
Please smoke test and give us final "go"

**Comment by davitol** [comment]
> @davitol Final is here https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.1
> Please smoke test and give us final "go"

Go go go

**Comment by mmattel** [comment]
I think that this can be closed as 0.11.1 has been released on Marketplace December 2019
