### ISSUE TITLE
Closing cross gets shifted when we open a pdf file with files_pdfviewer: 0.11.1

### ISSUE THREAD

**Issue by davitol** [owncloud/files_pdfviewer#202]
![Screen Shot 2019-12-10 at 10 34 34](https://user-images.githubusercontent.com/10596560/70525807-71db1580-1b48-11ea-9d51-d55d986b66b4.png)

(cc @VicDeo @HanaGemela @micbar fyi)

Note: it happens randomly.  Tested and reproducible with Firefox and Chrome for Mac.

Reproducible with files_pdfviewer: 0.11.1. Was not able to reproduce it with files_pdfviewer 0.9.0.

**Comment by VicDeo** [comment]
I never had something like this.
Probably reproducible on high density displays (retina) only.

**Comment by ChrisEdS** [comment]
> I never had something like this.
> Probably reproducible on high density displays (retina) only.

Yes. I think so, too. When I try to reproduce on a normal display there is no issue.

**Comment by davitol** [comment]
@ChrisEdS In my MacBook Pro (Retina, 13-inch, Early 2015) it does not happen, but same browser, server, tab etc moving to my Samsung display it gets shifted

**Comment by VicDeo** [comment]
may be resolution also matters here

**Comment by VicDeo** [comment]
is claimed to be fixed in https://github.com/owncloud/files_pdfviewer/pull/246
