### ISSUE TITLE
Cannot close a pdf opened from an attachment inside pdf documents

### ISSUE THREAD

**Issue by davitol** [owncloud/files_pdfviewer#203]
## Steps to reproduce

1-  Open attachments inside pdf document (it is opened in a new tab, intended behaviour?)
2 - Try to close the attachment using the close cross Icon of the files pdfviewer.

## Expected behavior

The file is close and it is possible to go back to files view

## Current behavior

Close icon does not trigger any action.

![Screen Shot 2019-12-10 at 12 36 10](https://user-images.githubusercontent.com/10596560/70526455-ea8ea180-1b49-11ea-9fc5-4124ece76122.png)
<img width="960" alt="Screen Shot 2019-12-10 at 12 36 36" src="https://user-images.githubusercontent.com/10596560/70526460-ef535580-1b49-11ea-855a-d81d5193e835.png">

  @HanaGemela please triage (cc @VicDeo @micbar jfyi)

**Comment by micbar** [comment]
@VicDeo 
Like we just discussed. We could use the close icon to close the tab for attachments.

**Comment by VicDeo** [comment]
addressed in https://github.com/owncloud/files_pdfviewer/pull/205

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/files_pdfviewer/pull/205
