### ISSUE TITLE
Download button does not work in Chrome 83

### ISSUE THREAD

**Issue by geekanthony** [owncloud/files_pdfviewer#214]
When viewing a PDF using Google Chrome 83 (specifically 83.0.4103.61), clicking the download icon in the upper right does not work.  It does not trigger a download.

Download function works fine using Chrome 81 (81.0.4044.138).

I was originally running PDF Viewer 0.11.0.  Upgraded to 0.11.1 with no change.

**Comment by MPtacnikCZ** [comment]
Hi,
I dealt with it today modifying **previewplugin.js** file in /public_html/apps/files_pdfviewer/js/
I add **allow-downloads** to:
$iframe = $('<iframe id="pdframe" style="width:100%;height:100%;display:block;position:absolute;top:0;z-index:10;" src="'+viewer+'" sandbox="allow-scripts allow-same-origin allow-popups allow-modals allow-top-navigation **allow-downloads**" />'); 

I hope it will help you.

**Comment by geekanthony** [comment]
> Hi,
> I dealt with it today modifying **previewplugin.js** file in /public_html/apps/files_pdfviewer/js/
> I add **allow-downloads** to:
> $iframe = $('<iframe id="pdframe" style="width:100%;height:100%;display:block;position:absolute;top:0;z-index:10;" src="'+viewer+'" sandbox="allow-scripts allow-same-origin allow-popups allow-modals allow-top-navigation allow-downloads" />');
> 
> I hope it will help you.

This worked!!  Thank you so much!

**Comment by cortho** [comment]
confirmed for Chrome 86.0.4240 and files_pdfviewer: 0.11.2
