### ISSUE TITLE
PDF Viewer 0.11.2

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_pdfviewer#218]
Because of merge of: https://github.com/owncloud/files_pdfviewer/pull/217 (Fix load of character maps to allow proper rendering of some fonts)
And all the PR´s created 2020 and upcoming oC 10.5

@micbar @pako81 @jnweiger @davitol @HanaGemela

**Comment by HanaGemela** [comment]
@pako81 what is the priority of this release?

**Comment by pako81** [comment]
> @pako81 what is the priority of this release?

@HanaGemela low

**Comment by HanaGemela** [comment]
Currently no need to release https://github.com/owncloud/files_pdfviewer/pull/217
Patch has been delivered to a single affected customer 
Waiting for more fixes to come in cc @pmaier1

**Comment by HanaGemela** [comment]
### Reason

- Release needed for "ticket X", "feature Y"

### Product approval

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [ ] Generate Changelog
- [ ] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [ ] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [ ] Bump version in `info.xml` (no version suffix)
- [ ] Check php version dependency in `info.xml`
- [ ] Check minimum ownCloud version dependency in `info.xml`
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] Create github tag for `v${version}RC1` on release branch
- [ ] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [ ] Rename last RC tarball to final
- [ ] Create github tag for final `v${version}` on release branch
- [ ] Upload as Github release using changelog entries

### Publishing

- [ ] Upload tarball to marketplace (see handbook for details)
- [ ] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Rename QA milestone to `$version`
- [ ] Add a new 'Unreleased' section in CHANGELOG.md
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [ ] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol ready for testing https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.2RC1
Setting as P2 for BTR team, this release is more important than the other apps

**Comment by davitol** [comment]
## 'PDF Viewer' Test Plan

- Run Testplan with browsers: Internet Explorer 11, MS EDGE, Mozilla Firefox, Chrome and Safari.

**Note**: Testplan has been run with Firefox and Chrome

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable files_pdfviewer app via CLI using ```occ app:enable files_pdfviewer``` | The apps gets enabled | ✅   |
Disable files_pdfviewer app via CLI using ```occ app:disable files_pdfviewer``` | The apps gets disabled | ✅  |
**Web UI** |  |   |
|  |   |
Enable files_pdfviewer app via webUI | The apps gets enabled | ✅  |
Disable files_pdfviewer app via webUI | The apps gets disabled | ✅  |
**Files View** |  |   |
|  |   |
Open a pdf file | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  |
**Favorites section** |  |   |
|  |   |
Make favorite a pdf file and open it from favorite section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅ |
**Share with you section** |  |   |
Receive a pdf file and open it from share with you section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  |
**Share with others section**|  |   |
|  |   |
Share a pdf file and open it from share with others section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  |
**Share by link section**|  |   |
|  |   |
Share a pdf file via link and open it from share by link section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  |
**Tag section**|  |   |
|  |   |
Tag a pdf file and search for tag and open it from tag section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅ |
**Public link**|  |   |
|  |   |
Share a pdf file via link and open it from the link| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  | 
**External Storage**|  |   |
|  |   |
Open a pdf file located in an external storage | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅ |
**Guest App**|  |   |
|  |   |
Open a pdf file using a guest user | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  |
**Impersonate App**|  |   |
|  |   |
Open a pdf file using an impersonated user | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | ✅  |


Changelog: open a pdf document containing Japanese characters through the files_pdfviewer app and check that fonts are correctly displayed. ✅

**Comment by davitol** [comment]
> @davitol ready for testing https://github.com/owncloud/files_pdfviewer/releases/tag/v0.11.2RC1
> Setting as P2 for BTR team, this release is more important than the other apps

@HanaGemela Tarball is QA-ready
