### ISSUE TITLE
Print scaling issue

### ISSUE THREAD

**Issue by icomputeUK** [owncloud/files_pdfviewer#221]
When users print, all pages are around 3/4 of the size they should be (they look file using the pdf viewer).

We're using Version 0.11.2 and the error has been reported by users using many different browsers.

![image](https://user-images.githubusercontent.com/32702985/92480325-a6b1f100-f1dc-11ea-8bfd-eba3bd411de4.png)

**Comment by JanAckermann** [comment]
Can you please try the new version 0.12.0 ?

**Comment by icomputeUK** [comment]
I updated to version 0.12.0 and then the files did not preview at all.

**Comment by JanAckermann** [comment]
Can you provide some screenshots and console output?`
