### ISSUE TITLE
Release files_pdfviewer 0.12.0

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_pdfviewer#230]
## Reason

After a series of important merges, a new release should be planned.
The last release from august has version 0.11.2
@micbar @jvillafanez 

- #228 - Update pdfjs to 2.5.
- #224 - make appstore fails on sign server
- #234 - Show Notification if downloading pdf is forbidden
- #237 - Enhance canDownload notification text
- #246 - Fix misalligned close X button
- #247 - Fix wrong locale settings
- #248 - Add translations

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server)) #253 
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [x] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date

**Comment by phil-davis** [comment]
For example, PR #228 was merged.

**Comment by micbar** [comment]
There are still more people complaining about https://github.com/owncloud/enterprise/issues/4280

@jvillafanez you say we cannot do something about it?

@hurradieweltgehtunter Can we get some exaple files from owncloud online?

**Comment by jvillafanez** [comment]
In theory, https://github.com/owncloud/files_pdfviewer/pull/228 should improve things. However, without a proper test file I'm not sure if that will be enough.

The new pdfjs version includes a parameter to set the image resolution. The PR has that parameter hardcoded to 300 dpi, which, as far as I've read around, should be enough for a good image quality. We can adjust the parameter if needed, but I haven't seen any noticeable difference using my test file.

I'd prefer to have a beta release so more people can verify whether they see an improvement or not.

**Comment by hurradieweltgehtunter** [comment]
> There are still more people complaining about [owncloud/enterprise#4280](https://github.com/owncloud/enterprise/issues/4280)
> 
> @jvillafanez you say we cannot do something about it?
> 
> @hurradieweltgehtunter Can we get some example files from owncloud online?

I contacted the customer to send us a test file. Will get back to you as soon I have it.

**Comment by hurradieweltgehtunter** [comment]
Customer told me that they can't send us the file :(

**Comment by mmattel** [comment]
Q: lookig at: https://github.com/owncloud/files_pdfviewer/issues/224 (make appstore fails on sign server). 
`...currently cannot build a daily-master-complete tar ball...`
What about to fix that and ask the customer to test with a test version to see if the issue is resolved?

**Comment by hurradieweltgehtunter** [comment]
If you're talking about the oc.online customer - fine with me. Although I must mention that they have no account currently, their trial account expired. Testing with that particular customer is not possible currently. They need some tine to decide if they want to go with oc.online

**Comment by mmattel** [comment]
#234 (merged)

**Comment by mmattel** [comment]
https://github.com/owncloud/files_pdfviewer/pull/237

**Comment by jnweiger** [comment]
This app has <default_enable/> in info.xml, is this intended?

**Comment by jvillafanez** [comment]
"blame" points to a commit from 9 years ago, so at least it hasn't been changed.

**Comment by mmattel** [comment]
Means we have the possibility to fix it now.
@jnweiger, mind to do this task?

**Comment by jnweiger** [comment]
Sure, I can change the default_enable. But I don't know when we do default_enable, and when we don't, it is more that I am curious to lean when and why ...

**Comment by ChrisEdS** [comment]
Raised the priority to p2-high. Please take care.

Thank you BTR-Team.

**Comment by jnweiger** [comment]
> Means we have the possibility to fix it now.
> @jnweiger, mind to do this task?

Which task? Changing default_enable? No, not without input.

**Comment by mmattel** [comment]
> There was no further input. I'l leave it as it is.

My suggestion instead writing `<default_enable/>` would be `files_pdfviewer`.
