### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by voroyam** [owncloud/files_pdfviewer#240]
Should have been fixed with https://github.com/owncloud/files_pdfviewer/pull/220

But a customer recently reported this issue again.

I tried the patch, but it did not help.

Issue description:

When you open the PDF file with files_pdfviewer and click on the download button - nothing happens.

![image](https://user-images.githubusercontent.com/24212810/104509970-c1f99680-55ea-11eb-9991-39d4779826bc.png)

In Safari it works flawlessly, but in Chrome it does not work. Even with the patch.

**Comment by VicDeo** [comment]
Given that #220 was merged in December 2020 and the latest app release had been in Aug 2020 no wonder it is still reproducible.
Did you try incognito mode to exclude browser caching?

**Comment by voroyam** [comment]
I wrote that it's reproducible even with the fix :)



> Did you try incognito mode to exclude browser caching?

yes. still no reaction from the download button.

**Comment by mmattel** [comment]
Colleagues,
after a nightmare of (re)setting up node to the required version incl all dependencies, I have compiled `files_pdfviewer` master successfully and enabled the app in my dev env. Using a standard pdf file, I was able to open it, and - most important - **was able to download it. absolutely no issues!**
Ubuntu 18.04, Chrome version 87.0.4280.141 (Official Build) unknown (64-bit)
Hope this helps

**Comment by VicDeo** [comment]
owncloud@master / files_pdfviewer@master

https://user-images.githubusercontent.com/991300/104612984-cf208f00-5697-11eb-9554-ebbea98c9a3a.mp4

**Comment by mmattel** [comment]
@voroyam 
@VicDeo and myself have the same positive outcome.
But we both are running a custom build from master. This is maybe the reason.
While accessing from my local machine oC 10.6.0 stable using opera and chrome, I can not download either.

**Comment by VicDeo** [comment]
I bet it's related to the setup and not to the app itself

**Comment by mmattel** [comment]
@voroyam just to get sure, have you compiled this master and provided the result to the customer?

**Comment by voroyam** [comment]
> @voroyam just to get sure, have you compiled this master and provided the result to the customer?
> 
> 

I compiled nothing. I just downloaded the app and patched it.

**Comment by mmattel** [comment]
This is the issue. Such repos are different than core because they need to be build/compiled. If you want to help your customer, you need to provide him such a build.

**Comment by voroyam** [comment]
The files_pdfviewer is an app that has releases. Why should I treat this app any different that let's say the wnd app. I honestly don't understand it. If the release is buggy then we need a new release that fixes the bugs, am I wrong?

It's also too much to ask from our customers to tell them - "Well, you just downloaded the app, didn't you? This is where you went wrong, you have to compile the app."

Our customer also don't have their severs running on a git clone from the master branch, they download the same tarballs with the server code in them as I did.

If the app only works when you do some extra magic on a magic branch then we should change this and provide a proper app. In my view anyways.

**Comment by VicDeo** [comment]
The chance that the issue is related to the app itself is quite low.
Anyway, you are welcome to push https://github.com/owncloud/files_pdfviewer/issues/230 forward to prove that.

**Comment by mmattel** [comment]
@voroyam the situation is quite normal in SW business. You can always tell the customer that ownCloud has identified the issue and already made a fix. A public release is on the way but may take it´s time. If he needs in the meanwhile a non-official build of the app - just to test if that fixes his issue, you can provide him such a custom build. Which is for testing purposes only... This is a standard procedure and nothing special.

**Comment by voroyam** [comment]
what are your steps to reproduce?

**Comment by mmattel** [comment]
* Use 10.6 stable with provided files_pdfviewer
* Client (in my case Windows und Ubuntu) has Chrome v 87.0.4280.141 installed
* Open pdf and try downloading --> fail
* Create a build of files_pdfviewer based on master and use that one for testing
* Open pdf and try downloading --> success

BTW, as Opera is based on Chrome (and I guess all browser who are based on Chrome) has the same issue - I tested also with Opera and got the same results as above.

**Comment by voroyam** [comment]
> * Use 10.6 stable with provided files_pdfviewer

more details please. where how why.

Can you reproduce this also with the downloadable stuff?

like: https://download.owncloud.org/community/owncloud-complete-20201216.tar.bz2
and : https://github.com/owncloud/files_pdfviewer/releases/download/v0.11.2/files_pdfviewer-0.11.2.tar.gz

**Comment by mmattel** [comment]
@voroyam stable = downloadable, you see the term _stable_ also in your instance and _git_ if you cloned it ect...

**Comment by voroyam** [comment]
So you can reproduce it with the stuff above?

**Comment by mmattel** [comment]
yes, not working with standard, working with compiled files_pdfviewer master = when released and published as new version, it provides the fix to customers.

**Comment by voroyam** [comment]
Great, thank you.

**Comment by voroyam** [comment]
if it's fixed in the new release - closing this then.
