### ISSUE TITLE
pdf file can't display correctly

### ISSUE THREAD

**Issue by orsfey** [owncloud/files_pdfviewer#243]
I found my pdf file can't display correctly on owncloud files_pdfviewer, 
![Capture](https://user-images.githubusercontent.com/39669047/106227454-1c951400-61e1-11eb-85c9-7165e4049ffd.PNG)
but when i test in nextcloud, i notice nextcloud files_pdfviewer plug can display without any problem,
![ntcd](https://user-images.githubusercontent.com/39669047/106227591-5a923800-61e1-11eb-8f6c-87a0c4c97249.PNG)
can anyone fix the problem?

here is the pdf file
[001 文件安全与权限.pdf](https://github.com/owncloud/files_pdfviewer/files/5891409/001.pdf)

**Comment by orsfey** [comment]
there are problem with this pdf 2, on owncloud plugin:
![Capture2](https://user-images.githubusercontent.com/39669047/106228010-561a4f00-61e2-11eb-90f2-c020f86adf1d.PNG)

on nextcloud files_pdfviewer plugin:
![捕获](https://user-images.githubusercontent.com/39669047/106228042-6cc0a600-61e2-11eb-8fa2-cac586fb753b.PNG)

the pdf file:
[clk011c-1.9.5.pdf](https://github.com/owncloud/files_pdfviewer/files/5891436/clk011c-1.9.5.pdf)

**Comment by VicDeo** [comment]
both files are displayed as expected for me. I tried master and the most recent v 0.11.2

**Comment by JanAckermann** [comment]
For me the same
