### ISSUE TITLE
Close button not on proper place

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/files_pdfviewer#245]
![image](https://user-images.githubusercontent.com/26169327/111635052-6371b400-87f7-11eb-8d6f-212b90bcf772.png)

**Comment by jnweiger** [comment]
Reopening. This fix does not seem to be in files_pdfviewer 0.12.0RC1 
The close button is misaligned as shown in the first screenshot in firefox, chrome, safari, edge.

**Comment by JanAckermann** [comment]
Please see https://github.com/owncloud/files_pdfviewer/pull/256

**Comment by jnweiger** [comment]
## Retesting with files_pdfviewer 0.12.0 RC2

On win10, IE11 and Edge don't show the X at all:

![image](https://user-images.githubusercontent.com/1108546/113926406-66573780-97ec-11eb-8168-12f6e3a1902d.png)

In Safari, Firefox, Chrome, the [ X ] sits perfect centered in place now!

**Comment by JanAckermann** [comment]
Oh No :/ will have a look

**Comment by JanAckermann** [comment]
@jnweiger fixed and backported
