### ISSUE TITLE
[QA] fails on IE11 with javascript syntax errors

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_pdfviewer#255]
Seen with files_pdfviewer 0.12.0-RC1 on server 10.7.0
Using IE11 11.973.17763.9 Uodate Versions 11.0.170

* Click on the User_Manual.pdf shipped with the server.

The PDF does not load, a dark empty window is shown. The scripting console has errors messages:

![image](https://user-images.githubusercontent.com/1108546/113780449-84129700-972f-11eb-82b2-9fe4c856234d.png)

**Comment by JanAckermann** [comment]
Here we go pdfjs 2.5 is ES6 which is not compatible with IE11 we need to use the ES5 version of it.

**Comment by GeraldLeikam** [comment]
Confirmed - Error occurs with Internet Explorer version 11.630.1904.0

**Comment by jnweiger** [comment]
confirmed fixed in 0.12.0 RC2
