### ISSUE TITLE
Error Message: The shared file does not have download permission and is possible protected by secure view

### ISSUE THREAD

**Issue by user1722** [owncloud/files_pdfviewer#265]
Hello,

since updating to 0.12 the following error message appears for every PDF files in a public shared folder.
Accessing the same PDF file in a share to the file direct works.
Accessing the same file when logged in on works.

The error message is:
The shared file does not have download permission and is possible protected by secure view, please contact the owner of the file for granting permission or use a different viewer.

Kind regards
user1722

**Comment by JanAckermann** [comment]
Thank you for opening the issue, the problem is identified and fixed :+1:
Needs a new version of files_pdfviewer, we are on it!
