### ISSUE TITLE
Download button not working on Webkit based browsers

### ISSUE THREAD

**Issue by jamu85** [owncloud/files_pdfviewer#275]
When viewing a pdf file in owncloud 10.7 with app version files_pdfviewer: 0.11.2, the download button in the pdf viewer has no functionality. On other browsers, the file will download.

**Comment by JanAckermann** [comment]
@JammingBen can you confirm this issue with Safari?

**Comment by JammingBen** [comment]
Not really, the file downloads for me when clicking the button.

**Comment by JanAckermann** [comment]
@jamu85 not able to reproduce,
can you provide more info ?

**Comment by jamu85** [comment]
On safari, I could not reproduce anymore but it was not working when I created the issue.
The attached gif shows how it looks from user perspective.

Browser console output shows

`
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.
`

![pdf-issue](https://user-images.githubusercontent.com/49803228/121383168-7979a700-c904-11eb-865b-490834472064.gif)

**Comment by jamu85** [comment]
Push, any new input especially on the "allow-downloads" flag

**Comment by jamu85** [comment]
Push, any updates?

**Comment by JanAckermann** [comment]
We are about to update the underlying pdfjs
