### ISSUE TITLE
Print size is scaled down, when document contains rotated pages

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_pdfviewer#278]
### Seen with files_pdfviewer 0.12.1 on 10.8.0-beta1 

* login as administrator, 
* upload the attached PDF, 
* click to view with the pdf viewer app,
* click on the print icon, a print preview appears
* the first page is shown as a portrait page scaled down towards the top left corner, 
* the second page is shown as a portrait page using the full width

<img src="https://user-images.githubusercontent.com/1108546/123641613-bad5e600-d822-11eb-9fbc-2005a0656a8a.png" width="50%"><img src="https://user-images.githubusercontent.com/1108546/123641849-fcff2780-d822-11eb-9b4e-549f2ac44798.png" width="50%"/>

Expected behaviour:
 * first page is portrait mode, scaled to 100% using the portrait paper to its magins.
 * second page is in landscape mode with short table,
 using the landscape paper to its horizontal margins.
 * compare with e.g. okular (or acroread):

<img src="https://user-images.githubusercontent.com/1108546/123642462-9c241f00-d823-11eb-8834-b1232cf97ddf.png" width="50%"/>

[JürgenWeigert.pdf](https://github.com/owncloud/files_pdfviewer/files/6726427/JurgenWeigert.pdf)

**Comment by jnweiger** [comment]
Not a regression. Reproduced in all tested versions.

**Comment by JanAckermann** [comment]
Not an files_pdfviewer issue itself, more a mozilla/pdf.js issue.
@jnweiger can you please create a ticket on the vendors repo ?
https://github.com/mozilla/pdf.js/issues
