### ISSUE TITLE
Release files_pdfviewer 0.12.2

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_pdfviewer#281]
Translations need to be included in the release tarball.
Fixes issue #279 PR #280

**Comment by phil-davis** [comment]
@micbar @jnweiger anyone like to make a branch, tag, tarball for this?

It looks easy (famous last words)

**Comment by micbar** [comment]
RC1 in https://github.com/owncloud/files_pdfviewer/releases/tag/v0.12.2RC1

**Comment by phil-davis** [comment]
- Installed from tarball files_pdfviewer-0.12.2RC1.tar.gz
- switched personal language setting to Deutsch
- uploaded a PDF
- the "Open with PDF Viewer" menu option is in Deutsch:

[Dateien - ownCloud.pdf](https://github.com/owncloud/files_pdfviewer/files/6765130/Dateien.-.ownCloud.pdf)

Looks good - translation is available.

**Comment by phil-davis** [comment]
The PDF viewer also has controls in Deutsch:
![Screenshot from 2021-07-05 20-55-12](https://user-images.githubusercontent.com/1535615/124491860-7377c880-ddd3-11eb-89b9-2a7f5d47f805.png)

**Comment by micbar** [comment]
@jnweiger Can you approve and publish?

**Comment by JanAckermann** [comment]
@phil-davis l10n in controls does not come from us, if the close button title (pop up) has a German translation, everything is fine (this comes from us)

**Comment by prsnbrg** [comment]
@micbar it's possible to publish this release on the marketplace?

**Comment by jnweiger** [comment]
This was closed too early. I almost missed the release tasks!

**Comment by jnweiger** [comment]
With German locale, almost everything is correctly translated. One exception: 
![image](https://user-images.githubusercontent.com/1108546/126348575-4620582d-597d-4270-9900-769a0d5eddf6.png)

-> not a blocker. Will release now.

**Comment by JanAckermann** [comment]
Release anyway, In the last release this was fixed now issue again....

**Comment by jnweiger** [comment]
> Maybe it is translated in de but not in de_De?

it says 'close' in both, de and de_DE. 
thanks. Releasing now.

**Comment by jnweiger** [comment]
@prsnbrg Release finally done. Sorry for the delay.

**Comment by JanAckermann** [comment]
@jnweiger changelog for l10n close fix has wrong PR link

**Comment by jnweiger** [comment]
> @jnweiger changelog for l10n close fix has wrong PR link

Ooops. Fixed on github releases and marketplace website. (But cannot fix it inside the released tar any more.)
