### ISSUE TITLE
Update pdf.js to v2.9 (to display digital signatures)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/files_pdfviewer#286]
**Version 2.9 of pdf.js  does now supports displaying of digital signatures** (but not verifying them)

We should update the pdf viewer to the latest version because we know that users (eg. in Italy) often need to display digital signatures (mainly relying on the PAdES standard, as the EU recognizes PAdES as eIDAS-compliant )
Releasenotes pdf.js: https://github.com/mozilla/pdf.js/releases/tag/v2.9.359

**funfact:** the request to display digital signatures via pdf.js is almost 10 years old (https://github.com/mozilla/pdf.js/issues/1076) so this is a historic step ;-)

**Comment by JanAckermann** [comment]
Tried to update some weeks ago.

Unfortunately, updating to a newer version breaks the app, so some investigations are necessary.

**Comment by VicDeo** [comment]
>v2.7.570 released this on Jan 24
This release features improved performance... ...support for IE 11 and non-Chromium-based Edge is dropped.

**Comment by JanAckermann** [comment]
@pmaier1 @micbar What should we do then, if IE11 gets not supported?

**Comment by micbar** [comment]
Then we have a problem 😓

**Comment by JanAckermann** [comment]
time for a private files_pdfviewer_v2 ? :/

**Comment by tbsbdr** [comment]
## Text proposal for a browser warning:
-------------
**Browser switch recommended**
Our website has detected that you are using an outdated browser that does not allow you to access all supported PDF features. Please switch to a modern browser for a better experience.

Please find here more information about supported browsers for viewing PDF files: https://github.com/owncloud/files_pdfviewer/releases/tag/[PLEASE ADD eg. v.1.0.0]

-------------

@JanAckermann is that contentwise correct and helpful?
Link to github is not nice, but maybe most helpful for Admins.
