### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/files_pdfviewer#294]

**Comment by GeraldLeikam** [comment]
Fail - Close

**Comment by VicDeo** [comment]
IE11 is not supported since 1.0.0, see https://github.com/owncloud/files_pdfviewer/issues/286#issuecomment-892611402

In short: we need pdf.js  v2.9 display digital signatures feature but IE11 is not supported by pdf.js since v2.7

So anyone who need IE11 support should use files_pdfviewer < 1.0.0
