### ISSUE TITLE
Links doesnt come up in new Tab or Window

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/files_pdfviewer#296]
In version v1.0.0rc1 of the files_pdfviewer, the links are not opened in a new tab or window but replace the content of the tab with the opened document.

![Screenshot_2021-09-09_14-45-11](https://user-images.githubusercontent.com/54261654/132688272-c6e2a1f7-871e-4e83-b548-cc72e3a84ecf.png)
![Screenshot_2021-09-09_14-45-46](https://user-images.githubusercontent.com/54261654/132688278-f19e2d57-8c19-492e-8ee0-ceaeef2649b3.png)

Occurs on the following browsers:

MS Internet Explorer
FireFox
Chrome
Android FireFox (doesn' work at all. see -> #298 )
Android Chrome (doesn' work at all. see -> #298 )

Safari and iOS Safari are still being tested.
As soon as these are tested I will update this issue.

**Comment by JanAckermann** [comment]
Well, the library again is not respecting the config 🤬 Will check with 2.10beta

**Comment by JanAckermann** [comment]
https://github.com/mozilla/pdf.js/issues/14033

Seems this is intended by mozilla
