### ISSUE TITLE
Gestures zoom does not work in pdf_viewer v1.0.0rc1

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/files_pdfviewer#297]
Zooming by gesture does not work if you open a pdf with our pdf_viewer v1.0.0.rc1 via the webfrontend in Android FireFox and Android Chrome. A document opened in this way can only be zoomed using the +/- buttons. This may not be a blocker, but it is a negative experience in terms of operation, as everyone is now used to zooming in on documents on their smartphones using a two-finger gesture.

**Comment by JanAckermann** [comment]
This is not supported by pdfjs yet https://github.com/mozilla/pdf.js/issues/2582
