### ISSUE TITLE
Release files_pdfviewer 1.0.1

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/files_pdfviewer#302]
# files_pdfviewer 1.0.1

### Reasons
- https://github.com/owncloud/files_pdfviewer/pull/301

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> https://github.com/owncloud/files_pdfviewer/issues/307
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [ ] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Test and document in testplan + manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [ ] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [ ] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [ ] Do changelog tests
    - [ ] Do regression tests
    - [ ] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [ ] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by JanAckermann** [comment]
Note: This is already possible to release, but we might wait until Mozilla releases pdfjs v2.10
FYI @pmaier1 @micbar

**Comment by JanAckermann** [comment]
After #305 popping up as well, we should take into consideration an early release -> moving to 'dev done, rc needed'

**Comment by GeraldLeikam** [comment]
Test plan skipped. 
Tested fixes only.

Fixes: 
- https://github.com/owncloud/files_pdfviewer/issues/296 :heavy_check_mark: 
- https://github.com/owncloud/files_pdfviewer/issues/298 :heavy_check_mark: 
- https://github.com/owncloud/files_pdfviewer/issues/305 :heavy_check_mark:

**Comment by JanAckermann** [comment]
@prsnbrg I vote for yes. 

1.0.1 was a bugfix release - so we didn't run the whole test plan, while updating to a new pdfjs this would be mandatory.
After this bugfix release I will update master to pdfjs 2.10

**Comment by JanAckermann** [comment]
So the issue is:
`Refused to frame 'https://cloud.tumas.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

You might need to update your apache or nginx configuration
https://geekflare.com/csp-frame-ancestors-configuration/

**Comment by daryl-farrugia** [comment]
@JanAckermann 

It worked!! Thanks a lot for your input and for noticing this.

**Comment by JanAckermann** [comment]
THX for feedback :+1:
