### ISSUE TITLE
Menu bar is not translated

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/files_pdfviewer#305]
Steps to reproduce
- Update files_pdfviewer to version 1.0.0
- Set Language of oC user to "Deutsch (Persönlich)"
- Open PDF File

![image](https://user-images.githubusercontent.com/29964525/133928921-1619716a-f4df-419e-88c6-92092adc25cb.png)

All buttons or texts except the Close button are not translated

**Comment by JanAckermann** [comment]
Thanks for opening this issue, this should be fixed with #301
