### ISSUE TITLE
eval-appliance-oc8ee: First page rendered blank

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_pdfviewer#37]
Tested the PDF viewer app as packaged in eval-appliance-oc8ee
downloaded from http://s2.owncloud.com:83/ee:/8.0/images_zip/eval-appliance-oc8ee.x86_64-2015.5.1-Build2.1.qcow2.zip

This is 8.0.0 RC1 running on openSUSE-13.1

Clicking on the ownCloudClientManual-1.7.pdf, the pdf viewer opens. The first page of the PDF is rendered all white with an rotaiting busy indicator. When scrolling down, all other pages appear to be there.

@MorrisJobke

**Comment by MorrisJobke** [comment]
@LukasReschke You touched pdf the last times ;)

**Comment by DeepDiver1975** [comment]
@jnweiger which browser on which os?

Anything in the browsers error console?

THX

**Comment by LukasReschke** [comment]
Also would be awesome if that PDF could be shared here. I have no idea how to access s2 from here ;-)

**Comment by DeepDiver1975** [comment]
http://doc.owncloud.org/desktop/1.7/ownCloudClientManual.pdf

**Comment by DeepDiver1975** [comment]
The problem is related to the pdf - it doesn't render here in pure firefox as well

**Comment by LukasReschke** [comment]
Upstream Issue then. Let's file an issue at https://github.com/mozilla/pdf.js/issues. I can do that later but now not. If somebody else wants to dive in: Feel free to ;-)
