### ISSUE TITLE
ownCloud 8 PDF Viewer Favorites, no correct display

### ISSUE THREAD

**Issue by igraf** [owncloud/files_pdfviewer#38]
ownCloud 8 Final

Hi
I have problems with pdf view in favorites. when open a pdf, the folder structure is displayed. Failure detected in several browsers.

Examples
https://drive.google.com/file/d/0B_JBqvP4UUXkSTJPSjBnRnBYRG8/view?usp=sharing
https://drive.google.com/file/d/0B_JBqvP4UUXkV0NaRWJ1VU5SbGs/view?usp=sharing

The key tools is not good visible and hinders the close button
https://drive.google.com/file/d/0B_JBqvP4UUXkeF9GSkloX09zNTg/view?usp=sharing

best regards

**Comment by LukasReschke** [comment]
Core issue: https://github.com/owncloud/core/issues/14536

**Comment by PVince81** [comment]
Works for me in 9.1.0beta2
