### ISSUE TITLE
preview pdf.js not working

### ISSUE THREAD

**Issue by ochsusd** [owncloud/files_pdfviewer#46]
PDF files generated via a certain printing device can not be displayed in owncloud.

Mozilla FireFox 36.0.1
Cloud 7.0.4 (stable)

Error Message after click on that file is:

[Could not load PDF file]
PDF.js v0.8.1136 (build: ca612e5)
Message: infoDict.has is not a function

PDF document property:

PDF Version 1.6 (Acrobat 7.x)

Adobe Acrobat xmp output for the PDF file:

<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.4-c005 78.147326, 2012/08/23-13:03:03        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:xmp="http://ns.adobe.com/xap/1.0/"
            xmlns:dc="http://purl.org/dc/elements/1.1/"
            xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
         <xmp:CreateDate>2015-03-05T22:01:26+01:00</xmp:CreateDate>
         <xmp:ModifyDate>2015-03-05T22:01:26+01:00</xmp:ModifyDate>
         <xmp:CreatorTool>BGD-PDF Library Ver. 3.4</xmp:CreatorTool>
         <dc:format>application/pdf</dc:format>
         <pdf:Producer>Business Graphics Datentechnik GmbH</pdf:Producer>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>

:edit:
owncloud version

**Comment by karlitschek** [comment]
this seems to be a bug in pdf.js. I recommend to report this bug to them. Thanks a lot
