### ISSUE TITLE
Error message shown after trying to open a deleted federated cloud share doesn't explain the cause, causing bad UX

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/files_pdfviewer#47]
### Steps to reproduce
1. Upload a pdf file and share it by link in server A
2. Add the link in server B
3. Delete the pdf file in server A
4. Open the file from server B with the pdf viewer

### Expected behaviour
The app warns the users that the file is missing and cannot be longer accessed, probably deleting the file in server B

### Actual behaviour
It just shows an error about not loading the file. Without any more information, this could be a temporary error (either in the server, the network...), so the user will likely retry to open the file, causing a bad UX because the error cause is unknown to the user.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by LukasReschke** [comment]
> Delete the image file in server A

:confused: – I don't get the problem - can you please rephrase it for dummies? Thanks :-)

**Comment by jvillafanez** [comment]
That happens when I copy and paste the steps from another issue :sweat_smile: 
You need to delete the pdf file uploaded in step 1

**Comment by jvillafanez** [comment]
I've updated the steps to make them clearer

**Comment by LukasReschke** [comment]
So basically it's the same such as deleting a file in another tab and opening it in a previously opened tab?  – Mhm, let me see if there is some way to catch this gracefully. Should be possible.

**Comment by jvillafanez** [comment]
Not exactly. You have 2 servers sharing a file through server to server sharing. The file you try to open is shared from the other server, and at some point that file is deleted

**Comment by LukasReschke** [comment]
Yeah. But technically it is the same thing that happens "the file does not exist more on the ownCloud server" - it's not in the file list - right?

If so I should be able to catch this _relatively_ easily.
