### ISSUE TITLE
files_pdfviewer does not pass occ app:check-code

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/files_pdfviewer#49]
### Steps to reproduce

1. Install 8.1 enterprise
2. invoke occ app:check-code

### Expected behaviour

The app passes the check

### Actual behaviour

The app fails the check:

```

[32mAnalysing /var/www/html/owncloud/apps/files_pdfviewer/tests/unit/controller/displaycontrollertest.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/files_pdfviewer/tests/bootstrap.php[39m
 1 errors
    [37;41mline   16: OC_Hook - static method call on private class[39;49m
[32mAnalysing /var/www/html/owncloud/apps/files_pdfviewer/templates/viewer.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/files_pdfviewer/controller/displaycontroller.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/files_pdfviewer/appinfo/app.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/files_pdfviewer/appinfo/routes.php[39m
 0 errors
[37;41mApp is not compliant[39;49m


```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by LukasReschke** [comment]
This is an error in the unit test bootstrapping => Irrelevant

**Comment by jnfrmarks** [comment]
If it's irrelevant than can we update occ app:check-code to ignore this issue?

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> If it's irrelevant than can we update occ app:check-code to ignore this issue?

yes - we shall not analyse test folders
