### ISSUE TITLE
files_pdfviewer is not ready for internet explorer 8

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_pdfviewer#54]
This app simply doesn't work in internet explorer 8 at all.

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG can you please test if the demo of pdf.js works in IE8? https://mozilla.github.io/pdf.js/

**Comment by LukasReschke** [comment]
It doesn't work. It is even documented in the appinfo file: https://github.com/owncloud/files_pdfviewer/blob/4d955cb2942027c57bc0b78440d7fbd034b0aeea/appinfo/info.xml#L13

See https://github.com/mozilla/pdf.js/wiki/Required-Browser-Features – what does "not work" mean? In the expected case it should do nothing at all and not get displayed. Though that seems to get lost by the last refactoring. Preparing PR…

**Comment by LukasReschke** [comment]
https://github.com/owncloud/files_pdfviewer/pull/55 brings back the "don't show PDF viewer at all behaviour."
