### ISSUE TITLE
Public sharing view of a PDF: double scrollbar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/files_pdfviewer#56]
When sharing a PDF, the PDF.js container extends below the viewport which results in a double scrollbar. One from PDF.js and one from us:
![owncloud shared pdf double scrollbar](https://cloud.githubusercontent.com/assets/925062/7614243/d42133ca-f995-11e4-99b9-f58fba038523.png)
We should make sure the PDF.js container is only as high as the viewport _minus_ the header height to remove our scrollbar.

cc @tomneedham @owncloud/designers

**Comment by JanAckermann** [comment]
Issue solved with owncloud 10.7 and files_pdfviewer 1.2.0

![image](https://user-images.githubusercontent.com/26169327/114839452-107b2480-9dd6-11eb-8855-62465ec23e9a.png)
