### ISSUE TITLE
PDF will not open

### ISSUE THREAD

**Issue by tony5** [owncloud/files_pdfviewer#66]
PDF files created on some scanners or exported from google docs with images will not open.
disabling CSP "content security policy" will fix this issue but not the best solution.
owncloud 8.1.3 all php versions including vbox VM image.

**Comment by LukasReschke** [comment]
Potentially fixed with https://github.com/owncloud/files_pdfviewer/pull/65, please open a new issue if this still persists. Also clean your cache :-)

**Comment by tony5** [comment]
@LukasReschke adding $policy->addAllowedImageDomain('*');  to  controller/displaycontroller.php does not work for me.

**Comment by Akhenaton** [comment]
Neither for me... simply doesn't work.

**Comment by LukasReschke** [comment]
> Potentially fixed with #65, **please open a new issue if this still persists.** Also clean your cache :-)

Also use the issue template and post a copy of the file as well as provide a test account to the instance (lukas at owncloud dot com)
