### ISSUE TITLE
[HALF-SOLVED] PDF will not open #66 - Fix #65 doesn't work for me.

### ISSUE THREAD

**Issue by Akhenaton** [owncloud/files_pdfviewer#67]
Hi,

@ LukasReschke commented 17 days ago
Fixes #63 and #60 and #66

 ==> This fix #65 doesn't work for me... running Firefox 41.0 on Linux. And yes, all my cache is cleared (browser AND assets directory). I still have a pdf file that open normally, with no errors, but shows white blank pages in Firefox 41.0. With local pdf readers it works normally.

Should i send you that "pdf" ?

Regards,

**Comment by LukasReschke** [comment]
> Should i send you that "pdf" ?

Yes.

**Comment by Akhenaton** [comment]
Hum, it's a 24 meg. pdf.... I can't attach such big file to a mail... Have you a ftp or another way ? Thanks !

**Comment by LukasReschke** [comment]
Please upload to https://s3.owncloud.com/owncloud/index.php/s/a1Idja3bJZWDlah

**Comment by Akhenaton** [comment]
Done ! Thank you !
Best Regards,

**Comment by LukasReschke** [comment]
Works here: ![2015-09-26_13-44-54](https://cloud.githubusercontent.com/assets/878997/10117371/c64c19e8-6454-11e5-88dd-14c8af8c5e50.png)

Please provide a test account to your instance (lukas at owncloud dot com). I can't debug this further otherwise.

**Comment by Akhenaton** [comment]
It"s very odd, because i have many others "pdf" file and they all opens normally. The only thing i can think of is that this very pdf is made of many assembled little pdf pages/files i consolidated into one pdf file with "pdf chain".

I've sent you a mail for a test account.

Best regards,

**Comment by Akhenaton** [comment]
I have installed Chromium 45.0.2454.85 and it works flawlessly !!!  :-)

**So it's only a matter with Firefox. (Firefox 41.0)**

Regards,

**Comment by tony5** [comment]
I don't know why this issue has been closed?
what is the solution for Firefox?

**Comment by Akhenaton** [comment]
Because i think it's not an ownCloud  "files_pdfviewer" issue, but rather a Firefox bug... Firefox is getting worst each new release... So i've closed the issue.

**Comment by srvdtrouble** [comment]
Another note as this Firefox display problem still persists.  The same PDF's that we are having trouble with, where some images are displayed with the pdfviewer, can be downloaded and dragged into the firefox browers and the load perfectly.  We have applied the "$policy->addAllowedImageDomain('*');" to our server.  Only fix at this point is to disable security.csp.enable in the about:config.
