### ISSUE TITLE
[IE 11] Printed PDFs are broken

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/files_pdfviewer#68]
A user reported:

> We found a problem in the pdf viewer in ownCloud version 8.1.3. If you try to print a pdf shown in IE 11, the printed output is formatted wrong (the documents spreads for example to multiple pages), even if it is  shown correctly in the browser. In Firefox, everything is working as 
> expected. 
### Steps to reproduce
1. Open PDF with IE11
2. Print
### Expected behaviour

Printed PDF should be identical to displayed PDF
### Actual behaviour

<img width="1920" alt="fullscreen_28_09_15_18_49" src="https://cloud.githubusercontent.com/assets/214010/10142300/2c0590de-6612-11e5-9042-9d02f57f56a5.png">
### Server configuration

**ownCloud version:** (see ownCloud admin page)
8.1.2

Oh, and I tried to reproduce this, and I've got:

<img width="1024" alt="ie11_-_win8_1" src="https://cloud.githubusercontent.com/assets/214010/10142478/3776ea02-6613-11e5-8ba2-9994940a2f8e.png">

@MorrisJobke Who can help here?

00003856

**Comment by LukasReschke** [comment]
I suspect this is an upstream issue, can you test with https://mozilla.github.io/pdf.js/web/viewer.html as well?

**Comment by michaelstingl** [comment]
@LukasReschke Yes, same problem with https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by LukasReschke** [comment]
Probably already filed at https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-ie11-specific then - not much we can do :speak_no_evil: :see_no_evil: :hear_no_evil:

**Comment by LukasReschke** [comment]
Probably https://github.com/mozilla/pdf.js/issues/6415: 

> The only way to solve this problem is to get an API similar to mozPrintCallback in other browsers (this API allows us to stream print jobs (i.e. render one page at a time) instead of having to draw all pages at once and then request the browser to print it.

:dancers:

**Comment by LukasReschke** [comment]
Incorrect printing https://github.com/mozilla/pdf.js/issues/3983, see https://github.com/mozilla/pdf.js/issues/3983#issuecomment-140344201:

> This is about PR https://github.com/mozilla/pdf.js/pull/6160 which we cannot merge until we know that it will not regress other browsers. This means that it has to be tested manually on all browsers (Firefox, Chrome, IE and probably Opera/Safari too) and different operating systems (Windows, Linux, OS X) before we can land this. There is no use in quickly merging this and then finding out that it fixes IE, but breaks Firefox or Chrome. If someone is willing to do the test work, please provide your findings on the PR.

> On top of that, we are a few days away from sending the new changes upstream, so we should only merge that PR after September 21 to avoid having to uplift bug fixes.

**Comment by michaelstingl** [comment]
@LukasReschke I would suggest to "hide" the print button in IE11. Users can download and print it.

**Comment by LukasReschke** [comment]
So what we have:

- IE crashes when printing huge files: Not fixable. (https://github.com/owncloud/files_pdfviewer/issues/68#issuecomment-145461083)
- IE printes invalid: Fixable. **Requires from our side to volunteer proper testing on all systems and browser combinations out there** (https://github.com/owncloud/files_pdfviewer/issues/68#issuecomment-145461586)

**Comment by LukasReschke** [comment]
> @LukasReschke I would suggest to "hide" the print button in IE11. Users can download and print it.

What happens if they press CTRL + P? Can you check as well?

**Comment by michaelstingl** [comment]
@LukasReschke I could test some Windows/IE combinations. I have many of https://dev.modern.ie/tools/vms/mac/ available for testing on my machine.

**Comment by michaelstingl** [comment]
@LukasReschke Argh, "CTRL + P" needs to be deactivated too in IE11. This is no "elegant" solution.

**Comment by michaelstingl** [comment]
@MorrisJobke @LukasReschke Any ideas how to fix this?

00004228

**Comment by MorrisJobke** [comment]
> @MorrisJobke @LukasReschke Any ideas how to fix this?

Manpower to test the printing with the patch on as many as possible browsers and report it upstream.

**Comment by butonic** [comment]
All we can do is try [the upstream patch](https://github.com/mozilla/pdf.js/pull/6160) and giving our users an eusy way to test this. Probably by shipping [the paper rulers](http://www.vendian.org/mncharity/dir3/paper_rulers/)?

**Comment by michaelstingl** [comment]
@MorrisJobke What is the status here?

**Comment by MorrisJobke** [comment]
> @MorrisJobke What is the status here?

I will create an downstream patch for this.

**Comment by MorrisJobke** [comment]
@michaelstingl On my list, but very low pro :(

**Comment by michaelstingl** [comment]
Printing with files_pdfviewer from IE11 still sucks in 9.0.2.

@butonic @MTRichards Any idea?

@cmonteroluque Could we get this covered by QA?

**Comment by cmonteroluque** [comment]
assigned to @jvillafanez to follow up. @rperezb ping

**Comment by rperezb** [comment]
@cmonteroluque what is the milestone of this one?

**Comment by PVince81** [comment]
Let's update pdf.js in 9.0.5 then

**Comment by BornToBeRoot** [comment]
Same problem in IE 11 / Chrome 51 

Seems like documents who are created with PDFCreater are broken.

Download and print in Adobe Reader is working fine.

**Comment by tfrdidi** [comment]
Have the same problem. Independent from the settings of IE11, both vanilla and company adjustments. But for me it works well on Firefox 45.3 (although it appends a white page) and Chrome 53. Could I deliver any further information on my settings that might help?
Should the milestone be updated? 9.0.5 is done.

**Comment by PVince81** [comment]
pdfjs was upgraded in 9.2 pre-alpha: https://github.com/owncloud/files_pdfviewer/pull/126

Can you check whether your PDFs work with that version ? You can grab a daily here: https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2

**Comment by PVince81** [comment]
I'm not too keen on backporting library updates

**Comment by tfrdidi** [comment]
Will the new pdfjs be part of the next stable owncloud release?

**Comment by PVince81** [comment]
Before it can be backported, people should report whether the upgrade fixed the problem on master / daily, see https://github.com/owncloud/files_pdfviewer/issues/68#issuecomment-255061105

**Comment by TheMrApostel** [comment]
I suspect that i wont be able to test that on my nextcloud Installation?

**Comment by felixboehm** [comment]
Is this still an issue in ownCloud version 9.1 or 10 ?
@davitol please test.

**Comment by PVince81** [comment]
PDFJs lib was updated in https://github.com/owncloud/files_pdfviewer/pull/146, please try again once 0.9.0 is released
