### ISSUE TITLE
shared links which show PDFs shows no pictures on OC 8.1

### ISSUE THREAD

**Issue by frompxkrat** [owncloud/files_pdfviewer#69]
hello .. i posted this already here:
https://forum.owncloud.org/viewtopic.php?f=31&t=30751

on the end, i downloaded this repostory and pushed it online .. but the problem is still unsolved

see here .. it's ok with firefox:
in oc 8.04 it shows a shared link correctly .. a PDF with pictures inside:
http://www.technobau.ch/cloud/index.php/s/bbEzLi4N8vj6hPR

or here .. pictures missing with firefox:
in oc 8.1.3 it shows the same type of PDF's without pictures! 
http://tvbusch.ch/oase/index.php/s/E9DvxF7qHn9Cw4c

i tried it on different installations

what else?

**Comment by LukasReschke** [comment]
Both links do work here on Firefox 41. Please provide more details.

**Comment by frompxkrat** [comment]
the second one show no pictures .. tested in firefox portable 37, 40, 41

**Comment by LukasReschke** [comment]
![2015-10-01_17-04-50](https://cloud.githubusercontent.com/assets/878997/10224501/933a89d2-685e-11e5-818c-962f360bc57f.png)
![2015-10-01_17-04-52](https://cloud.githubusercontent.com/assets/878997/10224517/ab344b2c-685e-11e5-907f-85631ee82381.png)

**Comment by frompxkrat** [comment]
also with portable-versions?
i deleted the cache's .. but still  the problem .. moment

**Comment by LukasReschke** [comment]
Well. I'm not going to install portable versions on my production system here. Also you should include which OS you're using etc.

**Comment by frompxkrat** [comment]
1. win 8.1 .. 
2. but the problem exist also on an other machine in chrome .. but the 2nd one  is not my machine and somewhere else
3. portable-versions are not installable .. they run directly

**Comment by frompxkrat** [comment]
there is an other issue with the toolbar in internet-explorer 11 .. it is not possible to scroll, why the owncloud-toolbar is over the pdf-toolbar

**Comment by LukasReschke** [comment]
> there is an other issue with the toolbar in internet-explorer 11 .. it is not possible to scroll, why the owncloud-toolbar is over the pdf-toolbar

Another issue = File a new issue. Also read https://github.com/owncloud/files_pdfviewer/blob/master/CONTRIBUTING.md

**Comment by frompxkrat** [comment]
in wich system you maked above pistures

**Comment by LukasReschke** [comment]
> in wich system you maked above pistures

OS X 10.11 with Firefox, Chrome behaves the same way.

**Comment by frompxkrat** [comment]
then it looks only as problem for windows-systems .. difficult?

in my system all chrome-variations works well (commodo, iron, chrome) .. also k-meleon-browser and ie 11 .. but not firefox 37 -41

**Comment by LukasReschke** [comment]
Please try to apply the changes in https://github.com/owncloud/core/commit/1a167dd5acdbfa771b0a32af93add0ffe5e4884f, the first two files should be sufficient.

**Comment by frompxkrat** [comment]
yes it works .. incredibel .. like magic .. wau -.. thanks man

**Comment by LukasReschke** [comment]
Good to know. Patch will be included with 8.1.4 and I still prefer St.Gallen over Zurich area ;-)

**Comment by frompxkrat** [comment]
;-) .. i can understand, but there is no lake

**Comment by LukasReschke** [comment]
> but there is no lake

Can live with that. Keeps the prices down ;-)

**Comment by frompxkrat** [comment]
LOL .. i am a lake-child .. no possible to be without wather .. sea would be good to ;-)

**Comment by frompxkrat** [comment]
ist dein vater in der seelsorge tärtig?
