### ISSUE TITLE
PDF will not open

### ISSUE THREAD

**Issue by niefra** [owncloud/files_pdfviewer#74]
hi,

I have a problem opening a pdf -document with chrome or firefox (current version). it works fine with safari and IE.

pdf-files version 1.5 are opened and version 1.4 is not opened. do you have any idea?

I have already tried #65. 

thanks
franz

**Comment by LukasReschke** [comment]
Please provide the file in question to us.

**Comment by niefra** [comment]
hi,

this is one of them. it is a scan in pdf-format.

franz
[hp_test_scan.pdf](https://github.com/owncloud/files_pdfviewer/files/33316/hp_test_scan.pdf)
