### ISSUE TITLE
Form fields are beeing ignored

### ISSUE THREAD

**Issue by team4music** [owncloud/files_pdfviewer#75]
As i said in the title, sadly pdf documents with formulars can't be used. There is not the possibility to click inside of a single form.
I attached some example file

[Unbenannt 1.pdf](https://github.com/owncloud/files_pdfviewer/files/34460/Unbenannt.1.pdf)

**Comment by LukasReschke** [comment]
We're using pdf.js please report rendering problems at https://github.com/mozilla/pdf.js. Thanks.

**Comment by PifPof73** [comment]
Seems still an issue.
I have posted it to the pdf.js team:
[https://github.com/mozilla/pdf.js/issues/10836](url)
