### ISSUE TITLE
update pdf.js to latest

### ISSUE THREAD

**Issue by felixboehm** [owncloud/files_pdfviewer#77]
I've tested several issues with the pdf viewer app and compared with the latest version here:
http://mozilla.github.io/pdf.js/web/viewer.html

Solved in newest version:
- lot of browser specific issues 
- missing images in pdf
- missing images while printing

Is it possible to bump the pdf.js version?

4074

**Comment by felixboehm** [comment]
@DeepDiver1975 
Can I help out doing hands on? Anything to know for that?

**Comment by PVince81** [comment]
@LukasReschke can you take care of this ?

**Comment by felixboehm** [comment]
#82 solves this issues
