### ISSUE TITLE
Open PDF links in a new tab

### ISSUE THREAD

**Issue by strugee** [owncloud/files_pdfviewer#78]
When I click on a link in my PDF, nothing happens. Looking at the error console, seems like the linked URL is replacing the PDF document, and it gets blocked by Content Security Policy. The solution is to open links in a new tab.

I'm on PDF Viewer 0.7, ownCloud 8.2.1.

**Comment by LukasReschke** [comment]
> When I click on a link in my PDF, nothing happens. Looking at the error console, seems like the linked URL is replacing the PDF document, and it gets blocked by Content Security Policy. The solution is to open links in a new tab.

Can you share the PDF file (lukas@owncloud.com) and also tell us which browser do you use?

**Comment by strugee** [comment]
@LukasReschke shared (hopefully?) via ownCloud federation, from `cloud.strugee.net`. I'm on Firefox Nightly, built 11/24/15. I also know that someone else has reproduced it in Chrome 46 (current stable).

**Comment by strugee** [comment]
FWIW, the PDF was generated from LibreOffice Writer.

**Comment by LukasReschke** [comment]
Thanks. I can reproduce with that file. Let me see what I can do about that.

**Comment by PVince81** [comment]
Any update ?
