### ISSUE TITLE
viewing a pdf, the browser back button does not bring you back to file view

### ISSUE THREAD

**Issue by mdonges** [owncloud/files_pdfviewer#79]
yes, using the x on the left right corner works around it.
its more intuitive to use the browese back button.

just nice to have, but nice to have ;)

**Comment by MorrisJobke** [comment]
Fixed in https://github.com/owncloud/files_pdfviewer/pull/80 - will be shipped with 9.0 and 8.2.2

**Comment by cstroe** [comment]
:+1:
