### ISSUE TITLE
Print should be possible via Ctrl+P

### ISSUE THREAD

**Issue by sedrubal** [owncloud/files_pdfviewer#89]
### Steps to reproduce
1. Open a PDF in OwnCloud
2. Hit <kbd>Ctrl</kbd>+<kbd>P</kbd>
3. Print
### Expected behaviour

The PDF should be printed.
### Actual behaviour

Something that looks like the html of the site will be printed.
### Server configuration

**Operating system**: `Ubuntu 14.04`

**Web server:** `Apache 2`

**Database:** `Maria DB`

**PHP version:** `5`

**ownCloud version:** `8.2.1`

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** only approved :tm: apps

**The content of config/config.php:** `...`

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** `Firefox 43.0`

**Operating system:** `Fedora 23`
#### ownCloud log (data/owncloud.log):

`...`
#### Browser log:

`...`

**Comment by JanAckermann** [comment]
Working with owncloud 10.7.0 and files_pdfviewer 1.2.0
