### ISSUE TITLE
scrolling file lists in public share greater than windows size not possible

### ISSUE THREAD

**Issue by roha4000** [owncloud/files_pdfviewer#90]
Commit 72069f4e20a7d10fa81f3c19703f8ca895ac8867 introduced a 100% heigth in *css/style.css*. This makes scrolling file lists larger than windows size impossible.

OC Version 8.2.2 EE

**Steps to reproduce**
* create folder
* share folder via link
* create a lot of files / folders in the shared folder
* visit the public link with a separate browser and reduce windows height

The list items cannot be scrolled which makes the last entries unavailable.

**Quick solution**
Uncomment line 3 in css/style.css. The file list is scrollable again but the white border at the bottom in pdf preview will reappear. You can also disable the files_pdfviewer app if you cannot modifiy files.

**Comment by fuerst** [comment]
Confirm that. See also issues https://github.com/owncloud/core/issues/21373, https://github.com/owncloud/core/issues/21203 and https://github.com/owncloud/core/issues/19886. Possible solution is to have PDF Viewer add a body class and use this to restrict its style to the PDF Viewer. Don't know though if an app can add body classes.

**Comment by LukasReschke** [comment]
@Henni Thoughts?

**Comment by mhzawadi** [comment]
Hi all,

This also affects the gallery app from a shared link, removing the css fixes issue.
OC v8.2.2 files_pdfviewer v 0.7

**Comment by brozkeff** [comment]
I confirm this issue for public shares - behaves the same on Firefox 43 and Chrome 47 on Linux Mint 17.2., Owncloud 8.2.2 and PDF viewer 0.7. 

Disabling PDF Viewer 0.7 indeed temporarily serves as a suboptimal workaround. Clearly the other issues mentioned by fuerst are more or less duplicates of this same bug, only the workarounds which CSS to modify differ.

When logged in as user (Firefox 43) no problems even with PDF viewer enabled.

**Comment by Henni** [comment]
Is this issue just occurring on 8.2.2 or can anyone also reproduce it on other versions of owncloud?

**Comment by mhzawadi** [comment]
Hi @Henni,

I only got this issue in OC8.2.2, it was fine in OC8.2.1.
A quick check on the css on 8.2.1 shows a very different style.css.

**Comment by Henni** [comment]
@mhzawadi thanks

**Comment by fuerst** [comment]
Same here: at ownCloud 8.2.1 and PDF Viewer 0.7 the height of the #content DIV is set to _initial_ by public.css.

**Comment by fuerst** [comment]
- Vertical scrolling fixed in file lists accessed by public share link.
- PDF file is displayed with full windows height - no white padding at bottom.

Works - thanks!
