### ISSUE TITLE
PDF Viewer doesn't load

### ISSUE THREAD

**Issue by Shadow-X2** [owncloud/files_pdfviewer#95]
Steps to reproduce
1. open pdf file in owncloud
2. pdf viewer does not load

Expected behaviour
Pdf viewer should load and display pdf

Actual Behavior
blank screen (attached png)
![owncloud blank screen](https://cloud.githubusercontent.com/assets/17110632/12873587/1f1b84de-cd8f-11e5-90dd-9dfc3c7df78e.png)
Tested on firefox 44.0 chrome 48 opera 34

Server configuration
ubuntu 14.04
apache 2.4.7
mysql 5.5.47
php 5.5.9
owncloud 8.2.2.2
PDF Viewer 0.7
upgraded from 8.2 using owncloud repo

**Comment by ErikPel** [comment]
Can you open your javascript console and give us the output if there is any?
To get the console use one of these hotkeys depending on your browser:
Ctrl + Shift + J on chrome
Ctrl + Shift + K in firefox

**Comment by Shadow-X2** [comment]
The javascript console output is below, It pointed me in the right direction. I had an nginx proxy setup in front of the server running owncloud. 

nginx proxy had add_header X-Frame-Options DENY; set, which was disabling the frame from loading.

I changed the option to SAMEORIGIN
add_header X-Frame-Options SAMEORIGIN;

That fixed the problem.

Thanks ErikPel

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
window.controllers is deprecated. Do not use it for UA detection. ace.js:1716:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:17117
Load denied by X-Frame-Options: https://owncloud.site.com/index.php/apps/files_pdfviewer/?file=%2Findex.php%2Fapps%2Ffiles%2Fajax%2Fdownload.php%3Fdir%3D%252FDocuments%26files%3DZFS%2520Compression.pdf does not permit framing. <unknown>
Error: Permission denied to access property "document"

**Comment by ErikPel** [comment]
Glad you got it fixed :)

**Comment by GabroSW** [comment]
I have a similar problem, someone I leave attached, (refuse connection)
![image](https://user-images.githubusercontent.com/121163425/209943956-675a9587-b0d4-43c0-86ff-94f13052a6da.png)
